import java.io.IOException;
import org.apache.hadoop.io.LongWritable;
import org.apache.hadoop.io.Text;
import org.apache.hadoop.mapreduce.Reducer;

public class Task1WikiStatsReducer extends Reducer<Text, LongWritable, Text, LongWritable> {

	@Override
	public void reduce(Text key, Iterable<LongWritable> values, Context context)
			throws IOException, InterruptedException {

		System.out.println(" In Task1WikiStatsReducer now!");
		/*
		 * pageViewCount will sum the number of page views for a specific wikipedia project.
		 */
		long pageViewCount = 0;

		/*
		 * loop through the values generated by the mapper
		 */
		for (LongWritable value : values) {			
			pageViewCount += value.get();
		}
		/*
		 * write the new aggregated result for the given key
		 */
		context.write(key, new LongWritable(pageViewCount));
	}

}
